name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - run: echo "fake publish python package"

  deploy-docs:
    runs-on: ubuntu-22.04
    needs: publish
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # mike requires full access to history and commits

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv pip install mkdocs-material==9.6.11 mike==2.1.3

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Deploy versioned docs
        run: |
          source .venv/bin/activate
          VERSION=${GITHUB_REF#refs/tags/v}
          # mike deploy "$VERSION" --update-aliases latest stable
          mike deploy --push --update-aliases "$VERSION" latest
          mike set-default "$VERSION"
